In [12]:
#Slicing 1D Array

nums = [0, 1, 2, 3, 4]

print(nums)
print()
print(nums[2:4])
print()
print(nums[2:])
print()
print(nums[:2])
print()
print(nums[:])
print()
print(nums[:-1])
print()

nums[2:4] = [8, 9]
print(nums)

[0, 1, 2, 3, 4]

[2, 3]

[2, 3, 4]

[0, 1]

[0, 1, 2, 3, 4]

[0, 1, 2, 3]

[0, 1, 8, 9, 4]


In [7]:
#Slicing 2D Array

import numpy as np

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(b)
print()
print(b[:, 1])
print()
print(b[-1])
print()
print(b[-1, :])
print()
print(b[-1, ...])
print()
print(b[0:2, :])
print()



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 2  6 10]

[ 9 10 11 12]

[ 9 10 11 12]

[ 9 10 11 12]

[[1 2 3 4]
 [5 6 7 8]]



In [8]:
#Loading Data from .csv file

import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape)
print(len(x_data))
print(x_data[:5])

print()
print('---------------------------')
print()

print(y_data.shape)
print(len(y_data))
print(y_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]

---------------------------

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [9]:
#Low-level Implementation

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

#데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

#모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

     # H(x) 계산
    hypothesis = x_train.matmul(W) + b # or .mm or @

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))


Epoch    0/20 Cost: 26811.960938
Epoch    1/20 Cost: 9920.530273
Epoch    2/20 Cost: 3675.298828
Epoch    3/20 Cost: 1366.260498
Epoch    4/20 Cost: 512.542419
Epoch    5/20 Cost: 196.896622
Epoch    6/20 Cost: 80.190987
Epoch    7/20 Cost: 37.038692
Epoch    8/20 Cost: 21.081335
Epoch    9/20 Cost: 15.178760
Epoch   10/20 Cost: 12.993677
Epoch   11/20 Cost: 12.183030
Epoch   12/20 Cost: 11.880535
Epoch   13/20 Cost: 11.765964
Epoch   14/20 Cost: 11.720856
Epoch   15/20 Cost: 11.701438
Epoch   16/20 Cost: 11.691510
Epoch   17/20 Cost: 11.685122
Epoch   18/20 Cost: 11.680007
Epoch   19/20 Cost: 11.675372
Epoch   20/20 Cost: 11.670942


In [10]:
#High-level Implementation wuth nn.Module

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

#데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

#모델 초기화
model = MultivariateLinearRegressionModel()

#optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 28693.490234
Epoch    1/20 Cost: 10618.750977
Epoch    2/20 Cost: 3936.015381
Epoch    3/20 Cost: 1465.219727
Epoch    4/20 Cost: 551.693726
Epoch    5/20 Cost: 213.934616
Epoch    6/20 Cost: 89.052269
Epoch    7/20 Cost: 42.876007
Epoch    8/20 Cost: 25.799639
Epoch    9/20 Cost: 19.482420
Epoch   10/20 Cost: 17.143093
Epoch   11/20 Cost: 16.274508
Epoch   12/20 Cost: 15.949721
Epoch   13/20 Cost: 15.825986
Epoch   14/20 Cost: 15.776565
Epoch   15/20 Cost: 15.754660
Epoch   16/20 Cost: 15.742919
Epoch   17/20 Cost: 15.734917
Epoch   18/20 Cost: 15.728307
Epoch   19/20 Cost: 15.722219
Epoch   20/20 Cost: 15.716357
