In [24]:
#Linear regression

#Data definition (What would be the grade if I study 4 hours?)

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

#Data

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

print(x_train) 
print(x_train.shape)
print()

print(y_train)
print(y_train.shape)




tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [25]:
#Weight Initialization
print()
W = torch.zeros(1, requires_grad=True)
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)


tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [26]:
#Hypothesis
print()
hypothesis = x_train * W + b
print(hypothesis)


tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [27]:
#Cost

print(hypothesis)
print()

print(y_train)
print()

print(hypothesis - y_train)
print()

print((hypothesis - y_train) ** 2)
print()

cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

tensor([[1.],
        [2.],
        [3.]])

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)

tensor(4.6667, grad_fn=<MeanBackward0>)


In [28]:
#Gradient Descent

optimizer = optim.SGD([W, b], lr = 0.01)

optimizer.zero_grad()
cost.backward()
optimizer.step()

print(W)
print(b)
print('--------------------------------')

hypothesis = x_train * W + b
print(hypothesis)
print('--------------------------------')

cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)
--------------------------------
tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)
--------------------------------
tensor(3.6927, grad_fn=<MeanBackward0>)


In [32]:
#Traning with Full Code

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W + b
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)      # MSE

    # cost로 H(x) 개선
    optimizer.zero_grad()   #zero_grad로 gradient 초기화
    cost.backward()         #backward로 gradient 계산
    optimizer.step()        #step으로 개선

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1000 W: 1.971, b: 0.066 Cost: 0.000633
