In [5]:
#View(reshape)

import numpy as np
import torch

t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape) 

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)



torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [10]:
#Squeeze

ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)
print('------------------------------')

#Unsqueeze

ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print()

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
print()

print(ft.view(1, -1))
print(ft.view(1, -1).shape)
print()

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)
print()

print(ft.squeeze(-1))
print(ft.unsqueeze(-1).shape)
print()

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
------------------------------
torch.Size([3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([0., 1., 2.])
torch.Size([3, 1])



In [13]:
#Type Casting

lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print()

print(lt.float())
print()

bt = torch.ByteTensor([True, False, False, True])   #bool값 저장
print(bt)
print()

print(bt.long())
print(bt.float())
print()

tensor([1, 2, 3, 4])

tensor([1., 2., 3., 4.])

tensor([1, 0, 0, 1], dtype=torch.uint8)

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])



In [15]:
#Concatenate (이어붙이는것)

x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))


tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [17]:
#Stacking

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))
print()

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [19]:
#Ones and Zeros

x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print()

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
#In-place Operation

x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.))   #메모리를 할당하지 않고 연산가능
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
