In [ ]:
#1차원 : 벡터, 2차원 : 행렬, 3차원 : 텐서 
#2D Tensor |t| = (batch size, dim)
#3D Tensor |t| = (batch size, width, height) (vision)
#3D Tensor |t| = (batch size, length, dim)  (NLP)

In [3]:
#numpy 리뷰

import numpy as np
import torch 

t = np.array([0., 1., 2., 3., 4., 5., 6.,])
print(t)

print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape) 

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)


In [4]:
#1차원 파이토치

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.,])
print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

#2차원 파이토치

t = torch.FloatTensor([[1., 2., 3.,],
                       [4., 5., 6.,],
                       [7., 8., 9.,],
                       [10., 11., 12.]
                       ])
print(t)
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])


tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [5]:
#Broadcasting

#same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

#Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])     #3->[[3,3]]
print(m1 + m2)

#2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)
print('--------------------')

print()
print('--------------')
print('Mul vs Matmul')
print('--------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)  # 2x2
print('Shape of Matrix 2: ', m2.shape)  # 2x1
print(m1.matmul(m2))    #2x1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)  # 2x2
print('Shape of Matrix 2: ', m2.shape)  # 2x1
print(m1*m2)    #2x2
print(m1.mul(m2))



tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])
--------------------

--------------
Mul vs Matmul
--------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [7]:
#mean

t = torch.FloatTensor([1, 2])
print(t.mean())

#Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))


tensor(1.5000)
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [9]:
#sum

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))


tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [10]:
#Max and Argmax

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.max())

print(t.max(dim=0))
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])      #인덱스 값을 리턴

print(t.max(dim=1))
print(t.max(dim=-1))


tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
